### ISSUE TITLE
Players crash when they join the server

### ISSUE THREAD

**Issue by IAB007** [Gerrygames/ViaRewind#75] opened 2018-03-24 22:57 UTC
When players are joining the server, they are kick with this crash message : https://pastebin.com/Cv9CxkNT 

I think it's because of the special characters (like heart that I've got on minecraft tools). There is no log in the server console and I used minecraft 1.8.9 for my tests with BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:aef3861:1294 (with spigot 1.11.2)

Thank you and sorry for my bad english

**Comment by EvilSlime** [comment] 2018-03-31 09:01
IAB not all 1.7 versions works as I know only 1.7.10 works for my server.

**Comment by IAB007** [comment] 2018-03-31 12:38
As I said, I’ve tested with a 1.8.9 client, and it’s not working. For the moment, the 1.7 is not a priority for me.

**Comment by Gerrygames** [comment] 2018-04-06 13:46
This seems to be caused by a skull item with an invalid skin url. The base64 decoded texture value: "{textures:{SKIN:{url:"URL"}}}". I guess the invalid URL is ignored by newer clients. But this will be down to some plugin settings this invalid metadata and will not be fixed by ViaRewind.

**Closed by Gerrygames** 2018-04-06 13:46 UTC
