### ISSUE TITLE
Dispenser's Not Opening (1.7.10)

### ISSUE THREAD

**Issue by rowan-smith** [Gerrygames/ViaRewind#26] opened 2018-02-05 12:57 UTC
https://gist.github.com/4832b508eab672f7f035b3f5f70b34b0

**Can't open dispenser in 1.7**
https://gyazo.com/7f716aac2b6680f98732a3e9f384283d

**Comment by Gerrygames** [comment] 2018-02-05 14:32
Opening dispensers is working for me. Are you sure this is not caused by any other plugin?

**Comment by rowan-smith** [comment] 2018-02-05 14:40
Works fine for me now, at the time I had no other plugins except those shown in the gist and was running vanilla clients.

**Comment by Gerrygames** [comment] 2018-02-05 14:50
I will close this then for now. If it does occur again just create a new post here.

**Closed by Gerrygames** 2018-02-05 14:50 UTC
